default_platform(:android)

platform :android do
  desc "lane for andriod firebase app distribution "
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk"
    firebase_app_distribution(
    app: "1:590956228106:android:474d4a3abde16e136379f3",
    apk_path: "../build/app/outputs/apk/release/app-release.apk",
    testers: "mamdouhanahamada@gmail.com,esamm612@gmail.com,rahmayasser747@gmail.com,coursesara1@gmail.com",
    release_notes: "3omran is sending new release to the friends ❤️😂",
    firebase_cli_token: ENV["FIREBASE_TOKEN"]
  )
  end
end
